### ISSUE TITLE
Scroll the concordance view via mouse or touchpad gestures

### ISSUE THREAD

**Issue by stranak** [czcorpus/kontext#403] opened 2015-05-22 13:26 UTC
The concordance (search result) view has scrollbars, but they only react to direct clicking and dragging over them. E.g. to scroll horizontally user often needs to scroll down first to see the scrollbar. Otherwise it seems the content is cut out and cannot be scrolled.

I think the concordance view should react to mouse wheel, touchpad gestures, etc. just like any other native elements.

In Firefox the mouse or touchpad at least scrolls the whole window when over the concordance. In Safari, when the pointer is over the concordance, scrolling breaks completely. This makes it more a bug then a feature request.

**Comment by tomachalek** [comment] 2015-11-02 13:46
Currently I have no Mac OS X environment available which makes resolving this issue quite complicated.

Speaking about mouse wheel. I am experimenting with the combination "Shift + mousewheel" allowing user to scroll the view horizontally (cursor must be over the area already). For me this has the advantage that vertical scrolling is still consistent no matter where the mouse cursor is. The problem is that such a function must be advertised clearly.

Can you please try our [testing KonText installation](https://kontext-test.korpus.cz) and report whether it behaves properly? The noted horizontal scrolling function is also there. The site works for anonymous users too - only with limited functionality.

Thank you.

**Comment by stranak** [comment] 2015-11-02 14:10
> On 02 Nov 2015, at 14:46, Tomas Machalek <notifications@github.com> wrote:
> 
> Currently I have no Mac OS X environment available which makes resolving this issue quite complicated.
> 
> Speaking about mouse wheel. I am experimenting with the combination "Shift + mousewheel" allowing user to scroll the view horizontally (cursor must be over the area already). For me this has the advantage that vertical scrolling is still consistent no matter where the mouse cursor is. The problem is that such a function must be advertised clearly.
> 
> Can you please try our testing KonText installation and report whether it behaves properly? The noted horizontal scrolling function is also there. The site works for anonymous users too - only with limited functionality.

Currently (Safari 9.0.1, Firefox 41.0.2) both instances (test and production) work like this with touchpad on a Mac: When the concordance is wide enough (either long context, or big font), the whole page scrolls, but the element with the concordance doesn't. It has its scroll bar at the bottom, but that only becomes obvious when one gets to that bottom of the page.

So in my opinion it is not OK. I have not tested with a mouse, I don't have one :-)

Pavel

**Comment by stranak** [comment] 2016-04-04 20:13
I just had a very quick look and the problem is definitely in JS, in the jspScrollable. When I disable JavaScript, scrolling is immediately back to normal. 

Just out of curiosity, why do you need all those js elements to make a table scrollable? Can't you just wrap the table in `<div style="overflow-x:auto;">` or something? That would also make the scrollbars look native in all the browsers and follow other platform conventions.

**Comment by tomachalek** [comment] 2016-04-05 06:48
I have used the JScrollPane library (it's the one producing the 'jspScrollable' element) to be able to configure specific key+mouse shortcuts (e.g. in v >= 0.8 shift+mouse wheel) and to style the scrollbar within a single convenient API/library. 

But due to miscellaneous problems and some negative feedback I am considering to remove the library and make things a bit simpler. Hopefully, the version 0.9 (which will be released in early summer) will resolve this problem. Backports will be possible too.

**Comment by stranak** [comment] 2016-04-10 18:14
I vote for the removal. Not really because of this issue, I am sure it can be solved within the framework, but I always find supporting platform conventions better, than heavy multi-platform apps. 

Such apps in the end work the same on all platforms (one aspect of consistency), but always a bit differently than other apps on the user's platform, breaking the other aspect of consistency. I think that Java apps (frontends) showed users do not like this. 

For instance this shift+wheel is a native action in OS X that you are just overriding by your implementation. The same is true for scrollbar behaviour: there are some system settings for it and users than expect them to work (and look) that way. This is why I personally vote for the removal :-)

**Comment by tomachalek** [comment] 2016-09-26 09:27
Any custom code controlling the discussed pane scrolling has been removed.

**Closed by tomachalek** 2016-09-26 09:27 UTC
Labels: bug, enhancement

**Comment by stranak** [comment] 2016-09-26 12:53
I can confirm that in the RC of Context 0.9 the issue is gone and horizontal scrolling works fine.
