### ISSUE TITLE
Sound playback issues when using query editing operations

### ISSUE THREAD

**Issue by dlukes** [czcorpus/kontext#4656] opened 2022-01-10 11:03 UTC
1. Run a query on a corpus with audio.
2. Click on the square brackets in the concordance -- sound plays back as expected.
3. Click on the KWIC to open the detail view, click on the loudspeaker icon -- sound plays back as expected
4. Edit the query via the breadcrumb navigation to something else.
5. Click on the square brackets in the concordance -- **no sound**. Playback only works via the loudspeaker icon in the detail view.

**Comment by dlukes** [comment] 2022-01-10 11:03
Let me know if you can't reproduce or if you need more information :)

**Comment by mzimandl** [comment] 2022-01-13 20:34
I couldn't replicate this so far.

**Comment by dlukes** [comment] 2022-01-13 21:13
Can't reproduce this anymore either, even using exactly the same queries and setup as originally. But I remember being slightly frustrated that KonText was generally sluggish at that point in time (late morning of January 10th), so maybe it was just one of the symptoms of some larger server health issues. It's weird that it manifested only when using query editing and replaying operations, but oh well :)

**Comment by tomachalek** [comment] 2022-01-27 12:30
It looks like I've been lucky and succeed to reproduce the issue.

**Comment by tomachalek** [comment] 2022-01-27 16:50
The issue will be fixed only in the upcoming v0.16.0.

**Closed** 2022-01-27 16:51 UTC
